---
- hosts: all
  become: true
  tasks:
    - name: remove old versions
      apt: name={{ item }} state=absent
      loop: [ 'docker', 'docker-engine', 'docker.io', 'containerd', 'runc' ]

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'aptitude', 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker-ce
      apt: name={{ item }} state=latest update_cache=yes 
      loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]

    - name: check if docker group present
      group:
        name: docker
        state: present
    
    - name: add user to docker group
      user:
        name: ubuntu
        group: docker
        append: yes
