- hosts: all
  become: yes
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: ensure zip is at the latest version
      apt: name=zip state=latest
